/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type HomePage = {
  _id: string
  _type: "homePage"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
}

export type Residential = {
  _id: string
  _type: "residential"
  _createdAt: string
  _updatedAt: string
  _rev: string
  address?: {
    country?: string
    streetName?: string
    streetNumber?: string
    city?: string
    province?: string
    zip?: string
  }
  map?: {
    isActive?: boolean
    lat?: number
    lng?: number
  }
  info?: {
    price?: number
    locals?: number
    rooms?: number
    bathrooms?: number
    privateNegotiation?: boolean
  }
  mainSpecs?: {
    commercialSquareMeters?: number
    condominiumExpenses?: number
    floor?: {
      value?:
        | ""
        | "basement-floor"
        | "sub-basement-floor"
        | "ground-floor"
        | "mezzanine-floor"
        | "raised-floor"
        | "first-floor"
        | "second-floor"
        | "third-floor"
        | "fourth-floor"
        | "fifth-floor"
        | "sixth-floor"
        | "multiple-floors"
        | "attic"
        | "last-floor"
        | "full-building"
        | "other"
      label?: string
    }
    conciergeService?: {
      value?: "" | "full-time" | "half-time"
      label?: string
    }
    constructionYear?: number
    heatingSystem?: {
      value?: "" | "centralized" | "independent" | "other"
      label?: string
    }
    energyClass?: {
      value?:
        | ""
        | "a4"
        | "a3"
        | "a2"
        | "a1"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "other"
      label?: string
    }
  }
  additionalSpecs?: {
    furnishing?: {
      value?: "" | "furnished" | "semi-furnished" | "kitchen-only" | "other"
      label?: string
    }
    garden?: {
      value?: "" | "private" | "public" | "private-public"
      label?: string
    }
    garage?: {
      value?: "" | "single" | "double"
      label?: string
    }
    parking?: {
      value?: "" | "covered" | "uncovered"
      label?: string
    }
    balcony?: boolean
    terrace?: boolean
    cellar?: boolean
    attic?: boolean
    tavern?: boolean
    alarmSystem?: boolean
    disabledAccess?: boolean
    airConditioning?: {
      value?: "" | "independent" | "centralized" | "preparation"
      label?: string
    }
    pool?: {
      value?: "" | "private" | "public"
      label?: string
    }
    tennisCourt?: {
      value?: "" | "private" | "public"
      label?: string
    }
  }
  contents?: {
    excerpt?: string
    description?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }>
    mainImage?: {
      landscape?: {
        asset?: {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: "image"
      }
      portrait?: {
        asset?: {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: "image"
      }
    }
  }
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: "slug"
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | HomePage
  | Residential
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./sanity/lib/queries/real-estates.ts
// Variable: RESIDENTIALS_QUERY
// Query: *[_type == "residential"] | order(_createdAt desc) {    _id,    address,    map,    mainInfo,    mainSpecs,    additionalSpecs,    contents,  }
export type RESIDENTIALS_QUERYResult = Array<{
  _id: string
  address: {
    country?: string
    streetName?: string
    streetNumber?: string
    city?: string
    province?: string
    zip?: string
  } | null
  map: {
    isActive?: boolean
    lat?: number
    lng?: number
  } | null
  mainInfo: null
  mainSpecs: {
    commercialSquareMeters?: number
    condominiumExpenses?: number
    floor?: {
      value?:
        | ""
        | "attic"
        | "basement-floor"
        | "fifth-floor"
        | "first-floor"
        | "fourth-floor"
        | "full-building"
        | "ground-floor"
        | "last-floor"
        | "mezzanine-floor"
        | "multiple-floors"
        | "other"
        | "raised-floor"
        | "second-floor"
        | "sixth-floor"
        | "sub-basement-floor"
        | "third-floor"
      label?: string
    }
    conciergeService?: {
      value?: "" | "full-time" | "half-time"
      label?: string
    }
    constructionYear?: number
    heatingSystem?: {
      value?: "" | "centralized" | "independent" | "other"
      label?: string
    }
    energyClass?: {
      value?:
        | ""
        | "a1"
        | "a2"
        | "a3"
        | "a4"
        | "b"
        | "c"
        | "d"
        | "e"
        | "f"
        | "g"
        | "other"
      label?: string
    }
  } | null
  additionalSpecs: {
    furnishing?: {
      value?: "" | "furnished" | "kitchen-only" | "other" | "semi-furnished"
      label?: string
    }
    garden?: {
      value?: "" | "private-public" | "private" | "public"
      label?: string
    }
    garage?: {
      value?: "" | "double" | "single"
      label?: string
    }
    parking?: {
      value?: "" | "covered" | "uncovered"
      label?: string
    }
    balcony?: boolean
    terrace?: boolean
    cellar?: boolean
    attic?: boolean
    tavern?: boolean
    alarmSystem?: boolean
    disabledAccess?: boolean
    airConditioning?: {
      value?: "" | "centralized" | "independent" | "preparation"
      label?: string
    }
    pool?: {
      value?: "" | "private" | "public"
      label?: string
    }
    tennisCourt?: {
      value?: "" | "private" | "public"
      label?: string
    }
  } | null
  contents: {
    excerpt?: string
    description?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
      listItem?: "bullet" | "number"
      markDefs?: Array<{
        href?: string
        _type: "link"
        _key: string
      }>
      level?: number
      _type: "block"
      _key: string
    }>
    mainImage?: {
      landscape?: {
        asset?: {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: "image"
      }
      portrait?: {
        asset?: {
          _ref: string
          _type: "reference"
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: "image"
      }
    }
  } | null
}>

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "residential"] | order(_createdAt desc) {\n    _id,\n    address,\n    map,\n    mainInfo,\n    mainSpecs,\n    additionalSpecs,\n    contents,\n  }': RESIDENTIALS_QUERYResult
  }
}
